### ISSUE TITLE
（建议）mini560 建议改改用咸鱼的华为12V模块转5V，3.3V

### ISSUE THREAD

**Issue by caizikun** [KCORES/KCORES-CSPS-to-ATX-Converter#14]
mini560 建议改改用咸鱼的华为12V模块转5V，3.3V，虽说二手，但工业级的东西可靠性还是不错的，比mini560强

**Comment by alphaarea** [comment]
PW22拆和焊的难度都太大，而且二手货源不稳定，不会更改设计
如果有需要可以自己修改PCB，在介绍里加相关项目
