### ISSUE TITLE
exit status 1 'class HardwareSerial' has no member named 'printf'; did you mean 'print'?  什么原因，怎么解决？

### ISSUE THREAD

**Issue by SDRC43** [KCORES/KCORES-CSPS-to-ATX-Converter#15]
验证时总是提示
exit status 1
'class HardwareSerial' has no member named 'printf'; did you mean 'print'?
是什么原因

**Comment by SDRC43** [comment]
KCORES_CSPS.cpp:90:18: error: 'class HardwareSerial' has no member named 'printf'; did you mean 'print'?
           Serial.printf("CSPS::readCSPSword() Missmatch checksum. addr: 0x%02x, chk: 0x%02x\n", dataAddr, cs);
                  ^~~~~~
                  print
exit status 1
'class HardwareSerial' has no member named 'printf'; did you mean 'print'?

**Comment by alphaarea** [comment]
把有printf的都整个注释掉

**Comment by SDRC43** [comment]
收到，谢谢，已按此解决



在 2022-05-20 16:07:50，"Alpha Area" ***@***.***> 写道：

把有printf的都整个注释掉
