### ISSUE TITLE
原理图ATX 24pin接线定义是否有错误呢？

### ISSUE THREAD

**Issue by lz00qs** [KCORES/KCORES-CSPS-to-ATX-Converter#4]
您好！我发现您原理图pdf中的ATX 24pin电源接口的5v和3.3v线序与维基百科的定义都相反（3.3v和5v的接线对调了），请问这个接线是否有误呢？
![image](https://user-images.githubusercontent.com/42072641/114349705-d70aa500-9b9a-11eb-812e-f11969f0dcf4.png)

**Comment by alphaarea** [comment]
ATX 24Pin模组接口为长城巨龙线序，如果需要自己做线可以按需调整线序或减少引脚

不建议两头都搞成ATX，那样走线太恶心了
