### ISSUE TITLE
3.3v和5v输出是否考虑加个自恢复保险

### ISSUE THREAD

**Issue by chraac** [KCORES/KCORES-CSPS-to-ATX-Converter#7]
RT，5v和3.3v的最大输出分别为10a和5a，对比其他电源是偏小的，然后某些2.5mm机械硬盘会需要5v供电，有没有可能瞬时电流过大导致烧坏dc dc模块？是否加个自恢复保险能避免这个问题？

**Comment by alphaarea** [comment]
DC-DC模块自带打嗝保护，任意一路保护后ATX监控IC会关闭主输出，安全上没有问题，不需要自恢复保险。

**Comment by chraac** [comment]
> DC-DC模块自带打嗝保护，任意一路保护后ATX监控IC会关闭主输出，安全上没有问题，不需要自恢复保险。

多谢回复，我把问题关了
